name: Releases

on:
  push:
    tags:
      - release-even-better-toml-*
  workflow_dispatch:

# TODO: github doesn't support regex matching in if expressions for some reason,
# so these jobs all expect zero-versioned release tags...

jobs:
  wait_for_ci:
    name: Wait for CI Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI
        run: echo Done

  get_version:
    runs-on: ubuntu-latest
    needs: ["wait_for_ci"]
    outputs:
      vscode-ext: ${{ steps.vscode-ext.outputs.version || '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Retrieve release version
        if: startsWith(github.ref, 'refs/tags/release-even-better-toml-')
        run: echo "version=$(echo ${GITHUB_REF#refs/tags/release-even-better-toml-})" >> $GITHUB_OUTPUT
        id: vscode-ext

  publish_vscode_extension:
    name: Publish VSCode Extension
    needs: ["wait_for_ci", "get_version"]
    if: startsWith(github.ref, 'refs/tags/release-even-better-toml-') || contains(fromJSON('["workflow_dispatch", "pull_request"]'), github.event_name)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest Rust toolchain
        run: |
          rustup update --no-self-update
      - uses: Swatinem/rust-cache@v2
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Enable latest yarn
        run: corepack enable
        working-directory: editors/vscode
      - name: Extension NPM Install
        run: yarn
        working-directory: editors/vscode
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Package Extension
        run: vsce package --baseImagesUrl https://raw.githubusercontent.com/tamasfe/taplo/master/editors/vscode --no-yarn # Microsoft doesn't support anything other than npm and yarn@v1
        working-directory: editors/vscode
      - name: Publish extension to microsoft marketplace
        # disable publishing vscode ext in tamasfe/taplo due to expired token
        if: github.event_name == 'push' && github.repository_owner != 'tamasfe'
        run: vsce publish --baseImagesUrl https://raw.githubusercontent.com/tamasfe/taplo/master/editors/vscode -p $VSCE_TOKEN --no-yarn
        working-directory: editors/vscode
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
